"""initial

Revision ID: eb4e9a926783
Revises: 
Create Date: 2024-05-31 15:43:18.390132

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb4e9a926783'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('parent_title', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('parent_url', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.FLOAT(), dimensions=1), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.Enum('CLIENT', 'SUPPORT_TECHNICIAN', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('question_answer')
    # ### end Alembic commands ###
